### ISSUE TITLE
A couple issues during deployment

### ISSUE THREAD

**Issue by cstrock** [puzzlepeaches/sneaky_proxy#1]
I ran in to a couple of issues with the Dockerfile and wanted to check if my fixes break anything:

Changed "python-certbot-apache" to "python3-certbot-apache"
--Dockerfile wasn't building as it couldn't find the "python-certbot-apache" package

Change ProxyPass and ProxyPassReverse from HTTPS to HTTP
--GoPhish doesn't use HTTPs for the default page, so it was producing "Reason: Error during SSL Handshake with remote server"

After those 2 changes, I was able to see the GoPhish 404 error and the address bar shows SSL.

Great set of docker images though and write up.  Thanks.

**Comment by puzzlepeaches** [comment]
I just pushed a commit to fix both issues described. I am going to try to add a variable in the future to allow the user to set if the ProxyPass variable is using HTTP or HTTPS. 

Thanks for the issue and kind words!

**Comment by puzzlepeaches** [comment]
Just an update: added a branch where you can specify HTTP or HTTPS in the .env file. Will merge to master after some testing.
