### ISSUE TITLE
Error with .yaml "Network: host"

### ISSUE THREAD

**Issue by sinllaves** [puzzlepeaches/sneaky_proxy#2]
When first ran the docker-compose build reported an error reading network: host in .yaml. I have removed that network line and it is running. 
But when i do docker-compose build i get a report of a non zero code return of 1:

**Comment by puzzlepeaches** [comment]
Please ensure that the version of docker-compose is up to date. See [here](https://docs.docker.com/compose/networking/). Please feel free to reach out via email or Twitter if you are having any other issues.
